config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :doctors, only: [:index, :show] do
    resources :appointments, only: :create
    resources :reviews, only: [:update, :create]
  end

  get '/dashboard', to: 'appointments#dashboard'
  get '/meet', to: 'meetings#meet'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :doctor
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true

  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  validates :specializations, :first_name, :last_name,
            :email, :phone_number, :about, presence: true

  has_many :reviews, dependent: :destroy 
  has_many :appointments, dependent: :destroy 
  has_many :articles, dependent: :destroy 
  belongs_to :user
  has_one_attached :avatar

  def average_rating
    rating = 0.0
    reviews.each { |review| rating += review.rating }
    reviews.empty? ? 0 : (rating / reviews.size).round(1)
  end

  def free_appointments
    forthcoming_appointments = appointments
                               .where('appointment_start > ?', Time.now)
                               .order(appointment_start: :asc)
    make_white_list(forthcoming_appointments).to_json
  end

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end

  private

  def make_white_list(appointments)
    white_list = {}

    appointments.each do |appointment|
      start_time = appointment.appointment_start.getlocal
      key = start_time.strftime('%d/%m/%Y')
      start_hour = start_time.hour

      white_list[key] = (9..20).to_a unless white_list.key?(key)
      white_list[key].delete(start_hour)
    end

    # today would require some special treatment to
    # remove free slots for which the hour has passed
    # and add free slots for the rest of the day if
    # there have been no appointments
    today = Time.now.getlocal.strftime('%d/%m/%Y')
    this_hour = Time.now.getlocal.hour.to_i

    if white_list[today].present?
      (9..this_hour).each { |hour| white_list[today].delete(hour) }
    else
      white_list[today] = (this_hour..20).to_a
    end

    white_list
  end
end

app/models/review.rb
class Review < ApplicationRecord
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: (1..5) }

  belongs_to :doctor
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true

  has_many :appointments
  has_many :reviews
  has_one :doctor
  has_one_attached :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def appointments
    doctor? ? doctor.appointments : super
  end

  def current_appointment
    now = Time.now
    start = Time.new(now.year, now.month, now.day, now.hour, 0, 0)
    next_hour = Time.new(now.year, now.month, now.day, now.hour + 1, 0, 0)
    appointments.find_by('appointment_start = ? and appointment_end = ?', start, next_hour)

    # Appointment.last
  end

  def doctor?
    doctor.present?
  end

  def full_name
    "#{first_name.capitalize} #{last_name.capitalize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def create
    appointment = Appointment.new(
      user: current_user,
      doctor: Doctor.find(params[:doctor_id]),
    )

    date, hour = params[:slot].split(' ')
    day, month, year = date.split('/')

    appointment.appointment_start = Time.new(year, month, day, hour)
    appointment.appointment_end = Time.new(year, month, day, hour.to_i + 1)

    if appointment.save
      redirect_to dashboard_path
    else
      #
    end
  end

  def dashboard
    now = Time.now
    this_hour = Time.new(now.year, now.month, now.day, now.hour)

    @appointment = current_user.current_appointment
    @past_appointments = current_user.appointments.where('appointment_start < ?', this_hour)
    @future_appointments = current_user.appointments.where('appointment_start > ?', this_hour)
    @reviews = current_user.reviews unless current_user.doctor?
  end
end

app/controllers/doctors_controller.rb
require 'json'

class DoctorsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @doctors = Doctor.all.map do |doctor|
      {
        doctor: doctor,
        specializations: JSON.parse(doctor.specializations),
        rating: doctor.average_rating
      }
    end
  end

  def show
    @doctor = Doctor.find(params[:id])
    @reviews = @doctor.reviews
    @articles = @doctor.articles
    @specializations = JSON.parse(@doctor.specializations)
    @rating = @doctor.average_rating
    @appointment = Appointment.new
    @appointments_white_list = @doctor.free_appointments
  end
end

app/controllers/meetings_controller.rb
require 'opentok'

class MeetingsController < ApplicationController
  def meet
    appointment = current_user.current_appointment
    @doctor = appointment.doctor.full_name
    if appointment.nil?
      #
    else
      load_meeting_variables appointment
    end
  end

  private

  def load_meeting_variables(appointment)
    opentok = OpenTok::OpenTok.new Figaro.env.opentok_api_key, Figaro.env.opentok_api_secret

    if appointment.session_id.present?
      @session_id = appointment.session_id
    else
      @session_id = opentok.create_session.session_id
      appointment.update(session_id: @session_id)
    end

    @api_key = Figaro.env.opentok_api_key
    @token = opentok.generate_token @session_id
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/dashboard.html.erb
<% unless @appointment.nil? %>
  <% start_time = @appointment.appointment_start.getlocal.strftime('%H:%M') %>
  <% end_time = @appointment.appointment_end.getlocal.strftime('%H:%M') %>
<% end %>

<div class="banner" style="background-image:linear-gradient(160deg, #0093E9 0%, #80D0C7 100%), url(https://images.unsplash.com/photo-1580121213375-c0ac4d96b1bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <% if current_user.doctor? %>
      <h1 class="doctors_title">Hello, Dr. <%= current_user.doctor.full_name %>!</h1>
    <% else %>
      <h1 class="doctors_title">Hello, <%= current_user.full_name %>!</h1>
    <% end %>
    <% unless @appointment.nil? %>
      <p>Yay, your appointment with Dr. <%= @appointment.doctor.full_name  %> is about to <span class="highlight pl-2 pr-2">start now!</span></p>
    <% else %>
      <p>You don't have any appointments for today, but check your future appointments to see what's ahead.</p>
    <% end %>
  </div>
</div>

<div class="position-relative" style="height: 1vh; width: 300vw; left: -109vw;">
  <div class="shape shape-bottom shape-fluid-x svg-shim text-white">
    <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z" fill="currentColor"></path></svg>
  </div>
</div>


<ul class="nav nav-tabs container mt-n10 justify-content-center" id="dashboard-tab-items" role="tablist">
  <% second_tab_link_class = @appointment.nil? ? "nav-link active" : "nav-link" %>

  <% if current_user.doctor? %>
    <!-- tabs for doctor users -->
    <% unless @appointment.nil? %>
      <li class="nav-item text-bold" role="presentation">
        <a class="nav-link active" id="current-appointment-tab" data-toggle="tab" href="#current-appointment" role="tab" aria-controls="home" aria-selected="true">
          Your Current Appointment
        </a>
      </li>
    <% end %>

    <li class="nav-item" role="presentation">
      <a class="<%= second_tab_link_class %>" id="future-appointments-tab" data-toggle="tab" href="#future-appointments" role="tab" aria-controls="profile" aria-selected="<%= @appointment.nil? %>">
        My Future Appointments
      </a>
    </li>
  <% else %>
    <!-- tabs for client users -->
    <% unless @appointment.nil? %>
      <li class="nav-item text-bold" role="presentation">
        <a class="nav-link active" id="current-appointment-tab" data-toggle="tab" href="#current-appointment" role="tab" aria-controls="home" aria-selected="true">
          Your Current Appointment
        </a>
      </li>
    <% end %>

    <li class="nav-item" role="presentation">
      <a class="<%= second_tab_link_class %>" id="past-appointments-tab" data-toggle="tab" href="#past-appointments" role="tab" aria-controls="profile" aria-selected="<%= @appointment.nil? %>">
        My Past Appointments
      </a>
    </li>

    <li class="nav-item" role="presentation">
      <a class="nav-link" id="future-appointments-tab" data-toggle="tab" href="#future-appointments" role="tab" aria-controls="profile" aria-selected="false">
        My Future Appointments
      </a>
    </li>

    <li class="nav-item" role="presentation">
      <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab" aria-controls="contact" aria-selected="false">
        My Reviews
      </a>
    </li>
  <% end %>
</ul>

<% second_tab_class = @appointment.nil? ? "tab-pane fade show active" : "tab-pane fade" %>

<div class="tab-content container" id="dashboard-tab-content">
  <% if current_user.doctor? %>
    <!-- doctors' contents -->
    <% unless @appointment.nil? %>
      <div class="tab-pane fade show active" id="current-appointment" role="tabpanel" aria-labelledby="home-tab">
        <%= render 'shared/dashboard_appointment',
          head_line: "Your appointment with #{@appointment.user.full_name} is open right now.",
          appointment: @appointment %>
        </div>
    <% end %>

    <div class="<%= second_tab_class %>" id="future-appointments" role="tabpanel" aria-labelledby="profile-tab">
      <%= render 'shared/dashboard_card', appointments: @future_appointments, review_allowed: false %>
    </div>
  <% else %>
    <!-- users' content -->
    <% unless @appointment.nil? %>
      <div class="tab-pane fade show active" id="current-appointment" role="tabpanel" aria-labelledby="home-tab">
        <%= render 'shared/dashboard_appointment',
          head_line: "Yay! Your appointment with Dr. #{@appointment.doctor.full_name} is open right now!",
          appointment: @appointment %>
      </div>
    <% end %>

    <div class="<%= second_tab_class %>" id="past-appointments" role="tabpanel" aria-labelledby="profile-tab">
      <%= render 'shared/dashboard_card', appointments: @past_appointments, review_allowed: true %>
    </div>

    <div class="tab-pane fade" id="future-appointments" role="tabpanel" aria-labelledby="profile-tab">
      <%= render 'shared/dashboard_card', appointments: @future_appointments, review_allowed: false %>
    </div>

    <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="contact-tab">
      <ul>
        <% @reviews.each do |review| %>
          <li>
            <p><%= review.date %></p>
            <p><%= review.doctor.full_name %></p>
            <p><%= review.content %></p>
            <%= render 'shared/rating', rating: review.rating %>
            <%= link_to 'Edit', doctor_review_path(review.doctor, review), method: 'patch' %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
 </div>

app/views/doctors/index.html.erb
<div class="banner" style="background-image:linear-gradient(160deg, #0093E9 0%, #80D0C7 100%), url(https://images.unsplash.com/photo-1580121213375-c0ac4d96b1bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <h1 class="doctors_title">Take a breath with one of our <strong>Specialist</strong></h1>
    <p>We have gathered World class specialist to guide you through your journey</p>

  </div>
</div>

<div class="position-relative" style="height: 1vh; width: 300vw; left: -109vw;">
  <div class="shape shape-bottom shape-fluid-x svg-shim text-white">
    <svg viewBox="0 0 2880 48" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M0 48h2880V0h-720C1442.5 52 720 0 720 0H0v48z" fill="currentColor"></path></svg>
  </div>
</div>


<div class="container up-container pt-4">
  <div class="row">
    <div class="col-4">
      <div class="card shadow p-4 no-border border-radius-8">
        <div class="d-flex flex-column align-items-center">
          <p class='text-green text-uppercase'>Total Specialists</p>
          <h2><%= @doctors.size %></h2>
        </div>
        <div id="div-specializations" class="btn-group-vertical"></div>
      </div>
    </div>

    <div class="col-8 radius-8 overflow-scoll vh-100">
      <div class="isotope-grid">
        <% @doctors.each do |doctor_hash| %>
          <% doctor = doctor_hash[:doctor] %>
          <% specializations = doctor_hash[:specializations] %>
          <% rating = doctor_hash[:rating] %>
          <% isotope_grid_item_class = "isotope-grid-item #{specializations.join(' ')}" %>
          <div class="<%= isotope_grid_item_class %>">
            <div class="doctor-card-index shadow p-4 mt-0">
              <%= link_to doctor_path(doctor), class: 'doctor-card-index-link' do %>
                <span></span>
              <% end %>
              <div class="doctor-card-avatar-rating-index">
                <% if doctor.avatar.attached? %>
                  <%= cl_image_tag doctor.avatar.key, crop: :fill %>
                <% end %>
                <%= render 'shared/rating', rating: rating %>
              </div>
              <div class="doctor-card-infos-index">
                <h2 class='text-green'>Dr. <%= "#{doctor.first_name} #{doctor.last_name}" %></h2>
                <p class='text-truncate' style='width: 10%'><%= doctor.about %></p>
                <h6 class="text-muted text-uppercase mt-4">Specializations</h6>
                <ul class='d-flex'>
                  <% specializations.each do |specialization| %>
                    <li class='badge badge-tag mr-2'><%= specialization %></li>
                  <% end %>
                </ul>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClearMind</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <div class="main-container">
      <%= yield %>
    </div>
     <!-- jQuery -->
    <%= render 'shared/footer' %>
  </body>

  <!-- These lines enable flash messages handled by devise -->
<!--   <%#= render 'shared/flashes' %>
  <p class="notice"><%#= notice %></p>
  <p class="alert"><%#= alert %></p> -->
  <!-- end -->
</html>

app/views/meetings/meet.html.erb
<div class="banner" style="background-image:linear-gradient(160deg, #0093E9 0%, #80D0C7 100%), url(https://images.unsplash.com/photo-1580121213375-c0ac4d96b1bc?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1950&q=80);">
  <div class="container">
    <h1 class="doctors_title">Your <span class='highlight pl-2 pr-2 rounded'>safe space</span> with Dr. <%= @doctor %></h1>
  </div>
</div>




<input type="hidden" id="opentok-api-data"
  data-api-key="<%= @api_key %>"
  data-session-id="<%= @session_id %>"
  data-token="<%= @token %>">

<div class="container align-center">
  <div id="videos" class="d-grid">
    <div id="publisher"></div>
    <div id="subscriber"></div>
  </div>
</div>

app/views/pages/home.html.erb
    <!-- ***** Welcome Area Start ***** -->
    <div class="welcome-area" id="welcome">

        <!-- ***** Header Text Start ***** -->
        <div class="header-text">
            <div class="container">
                <div class="row">
                    <div class="left-text col-lg-6 col-md-6 col-sm-12 col-xs-12" data-undo="enter left move 30px over 0.6s after 0.4s">
                        <h1><strong>Free Your Mind</strong></h1>
                        <p>Connect With our specialists and take Control of Your Life </p>
                        <%= link_to "Book Now", doctors_path, class: "main-button-slider" %>
                        <!-- <a href="http://localhost:3000/doctors/" class="main-button-slider">Book Now</a> -->
                    </div>
                    <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12" data-undo="enter right move 30px over 0.6s after 0.4s">
                        <%# <img src="assets/images/slider-icon.png" class="rounded img-fluid d-block mx-auto" alt="First Vector Graphic"> %>
                         <%= image_tag "mindfulness.svg", class: "rounded img-fluid d-block mx-auto" %>
                    </div>
                </div>
            </div>
        </div>
        <!-- ***** Header Text End ***** -->
    </div>
    <!-- ***** Welcome Area End ***** -->


    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-7 col-md-12 col-sm-12" data-undo="enter left move 30px over 0.6s after 0.4s">
                    <%# <img src="assets/images/left-image.png" class="rounded img-fluid d-block mx-auto" alt="App"> %>
                    <%= image_tag "video_call.svg", class: "rounded img-fluid d-block mx-auto" %>
                </div>
                <div class="right-text col-lg-5 col-md-12 col-sm-12 mobile-top-fix">
                    <div class="left-heading">
                        <h5>Talk With The Best specialists From Anywhere, AnyTime.</h5>
                    </div>
                    <div class="left-text">
                        <p>we provide <a href="#"> the best service on market</a>. Clients who live in remote areas or who have limited mobility or limited access to transportation may be more motivated to participate in online therapy. <br><br>
                        Online therapy decreases absences due to poor weather conditions or sickness, allowing clients to participate in therapy on a regular basis.</p>
                        <a href="#about2" class="main-button">Discover More</a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="hr"></div>
                </div>
            </div>
        </div>
    </section>
    <!-- ***** Features Big Item End ***** -->

    <!-- ***** Features Big Item Start ***** -->
    <section class="section" id="about2">
        <div class="container">
            <div class="row">
                <div class="left-text col-lg-5 col-md-12 col-sm-12 mobile-bottom-fix">
                    <div class="left-heading">
                        <h5>From The Comfort Of You Home</h5>
                    </div>
                    <p>Online therapy can be scheduled more frequently, as clients do not have to commute long distances.</p>
                    <ul>
                        <li>
                            <%# <img src="assets/images/about-icon-01.png" alt=""> %>
                            <%= image_tag "about-icon-01.png" %>
                            <div class="text">
                                <h6>Increased progress</h6>
                                <p> Since online therapy provides more intense therapy, it can accelerate progress.</p>
                            </div>
                        </li>
                        <li>
                            <%# <img src="assets/images/about-icon-02.png" alt=""> %>
                            <%= image_tag "about-icon-02.png" %>
                            <div class="text">
                                <h6>Better access to specialists</h6>
                                <p>Online therapy can allow individuals in remote areas to get help from specialists who may not be available in their geographic location.</p>
                            </div>
                        </li>
                        <li>
                            <%# <img src="assets/images/about-icon-03.png" alt=""> %>
                            <%= image_tag "about-icon-03.png" %>
                            <div class="text">
                                <h6>Psychological comfort</h6>
                                <p>Online therapy can help with eliminating the social stigma related to receiving mental counseling or other therapy.</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="right-image col-lg-7 col-md-12 col-sm-12 mobile-bottom-fix-big" data-undo="enter right move 30px over 0.6s after 0.4s">

                    <%= image_tag "home.svg", class: "rounded img-fluid d-block mx-auto" %>
                </div>
            </div>
        </div>
    </section>

app/views/shared/_dashboard_appointment.html.erb
<!-- head_line -->
<!-- appointment -->

<% doctor = appointment.doctor %>
<% user = appointment.user %>
<div class="dashboard-call-to-action">
  <!-- <h1><%#= head_line %></h1> -->

  <div>
    <% if doctor.avatar.attached? %>
      <%= cl_image_tag doctor.avatar.key, crop: :fill, class: 'dashboard-big-avatar' %>
    <% end %>

    <%= link_to meet_path, class: 'btn-flat btn-action' do %>
      <i class="fas fa-people-arrows"></i> Join Meeting
    <% end %>

    <% if user.avatar.attached? %>
      <%= cl_image_tag user.avatar.key, crop: :fill, class: 'dashboard-big-avatar' %>
    <% end %>
  </div>
  <p class="mt-3 text-uppercase">Good news: you don't need any 3rd party application for joining the meeting!</p>
</div>

app/views/shared/_dashboard_card.html.erb
<!-- appointments -->
<!-- review_allowed -->

<% if current_user.doctor? %>
  <div class="grid">
    <% appointments.each do |appointment| %>
      <% user = appointment.user %>
      <% date = appointment.appointment_start.getlocal.strftime('%b %d %Y') %>

      <div class="doctor-card-dashboard">
        <p class="p-date"><%= date %></p>

        <div class="doctor-card-avatar-rating-dashboard">
          <% if user.avatar.attached? %>
            <%= cl_image_tag user.avatar.key, crop: :fill %>
          <% end %>
        </div>

        <div class="doctor-card-infos-dashboard">
          <%= user.full_name %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="grid">
    <% appointments.each do |appointment| %>
      <% doctor = appointment.doctor %>
      <% date = appointment.appointment_start.getlocal.strftime('%b %d %Y') %>

      <div class="doctor-card-dashboard">
        <p class="p-date"><%= date %></p>

        <div class="doctor-card-avatar-rating-dashboard">
          <% if doctor.avatar.attached? %>
            <%= cl_image_tag doctor.avatar.key, crop: :fill %>
          <% end %>

          <%= render 'shared/rating', rating: doctor.average_rating %>

          <% review = doctor.reviews.find_by(user: current_user) %>
          <% if review_allowed && review %>
            <%= link_to 'Edit', doctor_review_path(review.doctor, review), method: 'patch' %>
          <% elsif review_allowed %>
            <%= link_to 'Review', '#', class: 'btn-flat' %>
          <% end %>
        </div>

        <div class="doctor-card-infos-dashboard">
          <%= link_to doctor_path(doctor) do %>
            <%= doctor.full_name %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flatpickr.html.erb
<input id="input-white-list-json" type="hidden" value=<%= appointments_white_list %>>

<%= form_with authenticity_token: true do |f| %>
  <%= f.text_field :start_time, id: "input-meeting-date", style: "display: none;",
    data: {
      controller: "flatpickr",
      flatpickr_date_format: "Y-m-d",
      flatpickr_min_date: Time.zone.now
    } %>
<% end %>

<!-- Modal from Bootstrap -->

<!-- Modal from Bootstrap -->

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
        <p>Made with love by ClearMind Team @Lewagon Dubai</p>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<%# <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%# <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <%= link_to 'Clear Mind', root_path, class: 'logo' %>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li class="scroll-to-section"><%= link_to 'Home', root_path, class: 'active' %></li>
                            <li class="scroll-to-section"><%= link_to 'About', '#' %></li>
                            <li class="scroll-to-section"><%= link_to 'Our Doctors', doctors_path %></li>
                            <%# <li class="submenu"> %>
                                <%# <a href="javascript:;">Drop Down</a>
                                <ul>
                                    <li><a href="">About Us</a></li>
                                    <li><a href="">Features</a></li>
                                    <li><a href="">FAQ's</a></li>
                                    <li><a href="">Blog</a></li>
                                </ul> %>
                            <%# </li> %>

                        <% if user_signed_in? %>
                            <li>
                                <%= link_to "Dashboard", dashboard_path %>
                            </li>
                            <li>
                            <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                            </li>
                        <% else %>
                            <li>
                                <%= link_to "Login", new_user_session_path %>
                            </li>
                        <% end %>


                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
</div>

app/views/shared/_rating.html.erb
<p class="p-rating" style="letter-spacing: 4px; font-size: 20px; margin: 10px auto;">
  <%#= "#{'⭐' * rating}#{rating.to_i == rating ? '' : '🌟'}" %>
  <span class="d-flex">
    <% rating.to_i.times do %>
      <i class="fas fa-star" style="color: #6610f2ad;"></i>
    <% end %>
  </span>
</p>